config/routes.rb
Rails.application.routes.draw do
  get 'earnings', to: "earnings#index"

  resources :rates, only: [:show, :update]
  resources :days
  root "home#index"

  devise_for :users

end

app/models/blackberry.rb
class Blackberry < ActiveRecord::Base
  belongs_to :day
  validates_presence_of :kg, :rate

  def sum
    kg * rate
  end
  
end

app/models/blueberry.rb
class Blueberry < ActiveRecord::Base
  belongs_to :day
  validates_presence_of :kg, :rate

  def sum
    kg * rate
  end
  
end

app/models/day.rb
class Day < ActiveRecord::Base
  default_scope { order('date ASC') }
  belongs_to :user
  has_one :blueberry, dependent: :destroy
  has_one :raspberry, dependent: :destroy
  has_one :blackberry, dependent: :destroy
  has_one :hour, dependent: :destroy
  accepts_nested_attributes_for :blueberry, :raspberry, :blackberry, :hour

  validates_uniqueness_of :date, scope: :user

end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :day
  validates_presence_of :amount, :rate

  def sum
    amount * rate
  end

end

app/models/raspberry.rb
class Raspberry < ActiveRecord::Base
  belongs_to :day
  validates_presence_of :kg, :rate

  def sum
    kg * rate
  end
  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :blueberry, :raspberry, :blackberry, :hour, :food
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  after_create :create_rate

  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  validates_presence_of :firstname, :lastname

  has_many :days, dependent: :destroy
  has_one :rate, dependent: :destroy

  def all_earnings
    sum = 0
    days.each do |d|
      sum += d.blueberry.sum + d.raspberry.sum + d.blackberry.sum + d.hour.sum + d.food
    end
    number_to_currency(sum, :unit=>'€')
  end

  def blueberry_amount
    kg = 0
    days.each do |d|
      kg += d.blueberry.kg
    end
    kg
  end

  def blueberry_value
    val = 0
    days.each do |d|
      val += (d.blueberry.kg * d.blueberry.rate)
    end
    number_to_currency(val, :unit=>'€')
  end

  def raspberry_amount
    kg = 0
    days.each do |d|
      kg += d.raspberry.kg
    end
    kg
  end

  def raspberry_value
    val = 0
    days.each do |d|
      val += (d.raspberry.kg * d.raspberry.rate)
    end
    number_to_currency(val, :unit=>'€')
  end

  def blackberry_amount
    kg = 0
    days.each do |d|
      kg += d.blackberry.kg
    end
    kg
  end

  def blackberry_value
    val = 0
    days.each do |d|
      val += (d.blackberry.kg * d.blackberry.rate)
    end
    number_to_currency(val, :unit=>'€')
  end

  def hour_amount
    amount = 0
    days.each do |d|
      amount += d.hour.amount
    end
    amount
  end

  def hour_value
    val = 0
    days.each do |d|
      val += (d.hour.amount * d.hour.rate)
    end
    number_to_currency(val, :unit=>'€')
  end

  def day_value
    val = 0
    days.each do |d|
      val += d.food
    end
    number_to_currency(val, :unit=>'€')
  end

  private
    def create_rate
      Rate.create(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protect_from_forgery with: :exception

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << [:firstname, :lastname]
    end


end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = current_user.days.decorate
    @day = Day.new
    @day.blueberry = Blueberry.new
    @day.raspberry = Raspberry.new
    @day.blackberry = Blackberry.new
    @day.hour = Hour.new
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
    @day.blueberry
    @day.raspberry
    @day.blackberry
    @day.hour
  end

  # POST /days
  # POST /days.json
  def create
    @day = current_user.days.build(day_params)
    if @day.save
      redirect_to days_path, notice: 'Dodano dniówke! :)'
    else
      flash[:danger] = 'Coś poszło nie tak, upewnij się czy nie podajesz złych parametrów.
                        Każde pole musi posiadać wartość, zostaw wartość 0 jeżeli nic nie uzbierałeś.
                        Pamiętaj, że każda dniówka musi mieć unikalną date, 
                        tzn nie możesz posiadać dwóch dniówek z identyczną datą.
                        Do połówek używaj \'.\' (kropek) zamiast \',\' (przecinków).'
      redirect_to days_path
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to days_path, notice: "Pomyślnie zaaktualizowano dniówke: #{@day.date}" }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: "Pomyślnie usunięto dniówke: #{@day.date}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    def check_user
      redirect_to days_path unless current_user == @day.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :food, 
                                  blueberry_attributes:[:id, :kg, :rate], 
                                  raspberry_attributes:[:id, :kg, :rate], 
                                  blackberry_attributes:[:id, :kg, :rate], 
                                  hour_attributes:[:id, :amount, :rate])
    end
end

app/controllers/earnings_controller.rb
class EarningsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_to_days
  
  def index
  end

  private
    def redirect_to_days
      redirect_to days_path if user_signed_in?
    end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :check_user
  # GET /rates
  # GET /rates.json
  expose(:rate)
  def show
  end

  def update
    rate = Rate.find(params[:id])
    if rate.update_attributes(rate_params)
      flash[:success] = "Kursy zostały zaktualizowane"
      redirect_to rate_path(rate.id)
    else
      flash[:danger] = "Coś poszło nie tak"
      render 'show'
    end
  end

  # GET /rates/1
  # GET /rates/1.json

  # GET /rates/1/edit

  # POST /rates
  # POST /rates.json

  # PATCH/PUT /rates/1
  # PATCH/PUT /rates/1.json


  # DELETE /rates/1
  # DELETE /rates/1.json

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def rate_params
      params.require(:rate).permit(:user_id, :blueberry, :raspberry, :blackberry, :hour, :food)
    end

    def check_user
      redirect_to days_path unless current_user == rate.user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/earnings_helper.rb
module EarningsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/days/edit.html.haml
=simple_form_for @day, html:{class: "form-inline well"} do |d|
  .form-group
    .input-group
      = d.label "Data: "
      = d.input :date, as: :date_picker, label: false
      = d.input :food, as: :hidden, input_html: { value: current_user.rate.food }
    .input-group
      = d.simple_fields_for :blueberry do |b|
        =b.label "Borówka: "
        =b.input :kg, label: false
        =b.input :rate, as: :hidden
        .input-group-addon
          %em kurs:
          %br
          =@day.blueberry.rate
    .input-group
      = d.simple_fields_for :raspberry do |r|
        =r.label "Malina: "
        =r.input :kg, label: false
        =r.input :rate, as: :hidden
        .input-group-addon
          %em kurs:
          %br
          =@day.raspberry.rate
    .input-group
      = d.simple_fields_for :blackberry do |b|
        =b.label "Jeżyna: "
        =b.input :kg, label: false
        =b.input :rate, as: :hidden
        .input-group-addon
          %em kurs:
          %br
          =@day.blackberry.rate
    .input-group
      = d.simple_fields_for :hour do |h|
        =h.label "Godziny:"
        =h.input :amount, label: false
        =h.input :rate, as: :hidden
        .input-group-addon
          %em kurs:
          %br
          =@day.hour.rate

  = d.button :button, class: "btn btn-success go-right" do
    Potwierdź

%em * Jeżeli chcesz zmienić kursy, musisz usunąć dniówke, ustawić odpowiednie kursy i dodać ją ponownie.

app/views/days/index.html.haml
.panel.panel-primary
  .panel-heading.bolder Dniówki
  %table.table
    %thead
      %tr
        %th Dzień
        %th Borówka
        %th Malina
        %th Jeżyna
        %th Godziny
        %th Wyżywienie
        %th Suma
        %th Akcje

    %tbody
      - @days.each do |day|
        %tr
          %td= day.date.strftime("%d/%m/%Y")
          %td
            =day.blueberry.kg
            %span.label.label-success="x#{day.blueberry.rate}"
          %td
            =day.raspberry.kg
            %span.label.label-success="x#{day.raspberry.rate}"
          %td
            =day.blackberry.kg
            %span.label.label-success="x#{day.blackberry.rate}"
          %td
            =day.hour.amount
            %span.label.label-success="x#{day.hour.rate}"
          %td
            =day.food
            %span.label.label-success x1
          %td= day.sum
          %td
            =link_to 'Edycja', edit_day_path(day), class: "btn btn-warning btn-sm", role: "button"
            =link_to 'Usuń', day, :method => :delete, :data => { :confirm => 'Jesteś tego pewny?' }, class: "btn btn-danger btn-sm", role: "button"
      %tr
        %td
        %td
        %td
        %td
        %td
        %td
        %td.active.bolder= current_user.all_earnings
        %td

%br
=simple_form_for @day, html:{class: "form-inline well hidden"} do |d|
  .form-group
    .input-group
      = d.label "Data: "
      = d.input :date, as: :date_picker, label: false, input_html: { value: Time.now.strftime("%d/%m/%Y") }
      = d.input :food, as: :hidden, input_html: { value: current_user.rate.food }
    .input-group
      = d.simple_fields_for :blueberry do |b|
        =b.label "Borówka: "
        =b.input :kg, label: false, input_html: { min: '0', value: '0' }
        =b.input :rate, as: :hidden, input_html:{ value: current_user.rate.blueberry }
        .input-group-addon
          %em kurs:
          %br
          =current_user.rate.blueberry
    .input-group
      = d.simple_fields_for :raspberry do |r|
        =r.label "Malina: "
        =r.input :kg, label: false, input_html: { min: '0', value: '0' }
        =r.input :rate, as: :hidden, input_html: { value: current_user.rate.raspberry }
        .input-group-addon
          %em kurs:
          %br
          =current_user.rate.raspberry
    .input-group
      = d.simple_fields_for :blackberry do |b|
        =b.label "Jeżyna: "
        =b.input :kg, label: false, input_html: { min: '0', value: '0' }
        =b.input :rate, as: :hidden, input_html: { value: current_user.rate.blackberry }
        .input-group-addon
          %em kurs:
          %br
          =current_user.rate.blackberry
    .input-group
      = d.simple_fields_for :hour do |h|
        =h.label "Godziny:"
        =h.input :amount, label: false, input_html: { min: '0', value: '0' }
        =h.input :rate, as: :hidden, input_html: { value: current_user.rate.hour }
        .input-group-addon
          %em kurs:
          %br
          =current_user.rate.hour

  = d.button :button, class: "btn btn-success go-right" do
    Potwierdź

%button.btn.btn-danger.hidden#cancel Anuluj

= link_to 'Dodaj dniówke', '#', class: "btn btn-info btn-lg", role: "button", id: "showday"

app/views/days/new.html.haml
%h1 New day

= render 'form'

= link_to 'Back', days_path

app/views/days/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_day_path(@day)
\|
= link_to 'Back', days_path

app/views/earnings/index.html.haml
.row
  .col-md-6.col-md-offset-3
    .panel.panel-warning
      .panel-heading
        %h3.panel-title.bolder.text-center Wypłata
      .panel-body
        %h3.text-center= "#{current_user.firstname} #{current_user.lastname}"
        %h4.text-center= "#{current_user.days.first.date.strftime("%d/%m/%Y")} - #{current_user.days.last.date.strftime("%d/%m/%Y")}"
        %h4.text-center= "Borówka= ilość: #{current_user.blueberry_amount} kg, wartość: #{current_user.blueberry_value}"
        %h4.text-center= "Malina= ilość: #{current_user.raspberry_amount} kg, wartość: #{current_user.raspberry_value}"
        %h4.text-center= "Jeżyna= ilość: #{current_user.blackberry_amount} kg, wartość: #{current_user.blackberry_value}"
        %h4.text-center= "Godziny= ilość: #{current_user.hour_amount}h, wartość: #{current_user.hour_value}"
        %h4.text-center= "Dni= ilość: #{current_user.days.count}, wartość: #{current_user.day_value}"
        %h4.text-center= "Suma: #{current_user.all_earnings}"
      

app/views/home/index.html.haml
.jumbotron
  %h1.text-center Witaj w aplikacji monitorującej zbieranie
  %p.text-center Zarejestuj się aby móc dodawać zbiory
  .text-center= link_to "Rejestracja", new_user_registration_path, class: "btn btn-lg btn-primary", role: "button"

app/views/layouts/_footer.html.haml
%footer.footer.well.well-sm.navbar-fixed-bottom
  %p
    Zbieranie borowki 2015
    %em Łukasz G.

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %span
        =link_to "Borówka", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse.navbar-right
      %ul.nav.navbar-nav
        -if user_signed_in?
          %li= link_to "Zarobki", earnings_path
          %li= link_to "Kursy", rate_path(current_user.rate)
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = "#{current_user.firstname} #{current_user.lastname}"
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                =link_to "Ustawienia", edit_user_registration_path
              %li.divider
              %li
                =link_to "Wyloguj", destroy_user_session_path, method: :delete
        -else
          %li=link_to "Zaloguj", new_user_session_path
          %li=link_to "Zarejestruj", new_user_registration_path

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  -key = "danger" if key == "alert"
  -key = "success" if key == "notice"
  %div{:class => "alert alert-#{key}", :role => "alert"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/layouts/application.html.haml
%html
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    %title Borówki

  %body
    =render 'layouts/header'
    .container-fluid
      =render 'layouts/messages'
      .row
        .col-lg-12
          = yield
    =render 'layouts/footer'

app/views/rates/show.html.haml
.row
  .col-md-6.col-md-offset-3
    %h1.text-center Aktualne kursy
    .panel.panel-warning
      .panel-heading
        %h3.panel-title Kursy:
      .panel-body
        %p Po aktualizacji kursów będą one automatycznie dołączone do każdej nowej dniówki, nie dotyczą one wcześniej dodanych dniówek. Jeżeli dniówka ma niepoprawny kurs, usuń ją, ustaw odpowiednie kursy i dodaj ponownie.
      %ul.list-group
        =simple_form_for rate do |r|
          -tab = [1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0]
          %li.list-group-item 
            = r.input :blueberry, collection: tab, label: "Borówka:", include_blank: false
          %li.list-group-item 
            = r.input :raspberry, collection: tab, label: "Malina:", include_blank: false
          %li.list-group-item 
            = r.input :blackberry, collection: tab, label: "Jeżyna:", include_blank: false
          %li.list-group-item 
            = r.input :hour, collection: [4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10], label: "Godziny:", include_blank: false
          %li.list-group-item 
            = r.input :food, collection: [7.0], label: "Wyżywienie:", include_blank: false
          %br
          = r.button :submit, 'Aktualizuj', class: "btn btn-warning btn-lg center-block"